language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- npm install -g bower polymer-cli web-component-tester
install:
- bower install
script:
- polymer lint
- polymer test
- polymer build
