language: node_js
node_js: stable
os: linux
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- npm install -g bower polymer-cli
install:
- polymer install --variants
script:
- polymer lint
- xvfb-run polymer test
- polymer build
